language: ruby
script: rake ci
rvm:
  - ruby-head
#  - 2.2.0 # has a bug affecting rdf gem:  https://github.com/ruby-rdf/rdf/issues/167
  - 2.1.5 # on stage box 2015-04-13
  - 2.1.3 # on dev box 2015-04-13
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - triannon-commits@lists.stanford.edu
