language: ruby
script: rake ci 
rvm:
  - 2.1.1
  - ruby-head
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - ndushay@stanford.edu
    - cabeer@stanford.edu
    - wmene@stanford.edu
